### ISSUE TITLE
Location Features Range

### ISSUE THREAD

**Issue by tarrencev** [jyhjinghwang/SegSort#3]
In the code snippet below, the comment mentions that the location features are returned with range -1 to 1 (for float). But it seems the code actually returns 0 to 1. Is the code correct?

https://github.com/jyhjinghwang/SegSort/blob/a0fb523d79594726b2acfac3abf3c8e29806a530/network/segsort/common_utils.py#L147-L176

**Comment by jyhjinghwang** [comment]
Hi Tarrence,

Thanks for the catch!
We tried both settings and [0, 1] works better.  I've pushed the fix.

Best,
Jyh-Jing

**Comment by tarrencev** [comment]
Great, thanks for the clarification!
