### ISSUE TITLE
For HED contours

### ISSUE THREAD

**Issue by yuchan-san** [jyhjinghwang/SegSort#6]
Hi

Could you tell me how to make HED and its conditions in detail?
1) Is color contour possible? The sample which you provided is grayscale though.
2) How did you decide contours level(color)? They seem to almost be dark contours since there are few white area. How many color are they on it (21 classes or random)?
3) How did you combine several gPb contours?

Yu-chan

**Comment by jyhjinghwang** [comment]
Hi Yu-chan,

The mask HED is not a contour map.  It is the oversegmentation of HED-owt-ucm and the threshold for ucm is around 0.5.  The color (grayscale level) is labeled from top left to bottom right, which doesn't mater.

Please refer to issue #4 about how to produce oversemgnetations from HED.

Best,
Jyh-Jing

**Comment by yuchan-san** [comment]
Thanks;
