### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by Jerwee814** [jyhjinghwang/SegSort#8]
Can I have the code for the t-SNE visualization of prototype embeddings?

**Comment by jyhjinghwang** [comment]
Hi @Jerwee814,

The t-SNE visualization code is written in several pieces and quite messy...  I currently don't have time to clean it up and share it here.  Sorry about it!
Here's the workflow that you could try:
1.  Save prototype segments during Tensorflow inference.
2. Perform t-SNE (reducing to 2D) on the prototype features that are already saved.
3. Associate prototype segments with their t-SNEed 2D features and draw them in the corresponding location.

Regards,
Jyh-Jing

**Comment by Jerwee814** [comment]
Thanks. That helps a lot！



发自我的iPhone


------------------ Original ------------------
